### ISSUE TITLE
Not able to set properties for a topic

### ISSUE THREAD

**Issue by krishanfrog** [Blizzard/node-rdkafka#305]
I have this sample code which fails when I try to set acks for a topic. Have the latest version of rdkafka - 2.2.0

`const kafka = require('node-rdkafka');`
`const producer = new kafka.Producer({
  'metadata.broker.list': 'localhost:9092',
  'dr_cb': true
});`
`const topicConfig = {'request.required.acks': -1};`
`producer.connect().on('ready', () => {
  const topic = producer.Topic('Dummy', topicConfig);
});`

Throws this error
`TypeError: producer.Topic is not a function`

**Comment by krystianity** [comment]
I think you are using the old API.
You can pass the topic config to the Producer constructor `new Producer(options, tconf);`

Furthermore there is no need to pass the option during produce calls.
Just call `producer.produce("topicname",..)` with a topicname.

**Comment by krystianity** [comment]
If your aim is to create a Kafka Topic, you can use a metadata call to help with topic creation.

**Comment by krishanfrog** [comment]
Don't want to create a topic. the alternate way to pass topic config to Producer constructor works.

But what do you mean by using the old API? The node module is the latest and has the latest code.

**Comment by krishanfrog** [comment]
@krystianity can you please mention what you mean by the old API?

**Comment by krishanfrog** [comment]
Facing a similar issue with the API queryWatermarkOffsets()

Get an error this._client.queryWatermarkOffsets is not a function. The underlying C++ implementation does not have this function. 

What is the root cause for this? @krystianity

**Comment by krystianity** [comment]
@krishanfrog With "old API" I was not referencing the version of the module, I was talking about the way you are calling the functions. These calls would have worked in < 1.9 but not in 2.x

**Comment by webmakersteve** [comment]
I removed support for individually configured topics. They caused big issues with the interplay between librdkafka's reference counting and node's garbage collection. It would have been a lot of work for what I see as very little gain.

The way to configure your topic now is to pass  the topic configuration into the constructor of the producer (or consumer). If `producer.Topic` is still somewhere in the docs it is my mistake for not removing it.

**Comment by krishanfrog** [comment]
ok thanks @webmakersteve. What about the queryWatermarkOffsets() method. Is that also deprecated? If yes is there any other way to get offset for a partition in a topic?

**Comment by webmakersteve** [comment]
`queryWatermarkOffset` is not deprecated! I would recommend using that to get the currently committed offsets for all the partitions you care about, if you need to know what they are before your application runs.  You can use the metadata from the broker to determine the number of partitions and the topic names.
