### PR TITLE
Use C++14 to be able to build using node v16.x

### LINKED ISSUE #885: Can't build on nodejs 16.0.0
**Environment Information**
 - OS ubuntu 20.04: 
 - Node Version 16.0.0:
 - NPM Version 7.0.0:
 - C++ Toolchain g++:
 - node-rdkafka version 2.1.0:

**Steps to Reproduce**

Just install package

**node-rdkafka Configuration Settings**
No context. Just can't build it coz in nodejs 16 new ver of v8. 

**Additional context**
`
npm ERR! /home/resation/.cache/node-gyp/16.0.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
npm ERR! /home/resation/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
`
[2021-04-22T16_45_22_674Z-debug.log](https://github.com/Blizzard/node-rdkafka/files/6359955/2021-04-22T16_45_22_674Z-debug.log)

### PR DESCRIPTION
**Pull request by alferpal**
Tries to fix #885

### CODE REVIEW

**Comment by iradul** [comment]
LGTM

**Comment by bigclap** [comment]
Thanks guys. 🤭🌬️🏄

**Comment by phracek** [comment]
We are trying to build node-rdkafka in container but it failed with 
```
```

**Comment by yunnysunny** [comment]
The `-std=c++14` flag is not supported on GCC 4.8, which is the version used by centos 7. In other words, the compile will be failed in centos 7.
See more on this link https://stackoverflow.com/questions/31965413/compile-c14-code-with-g .

**Comment by alferpal** [comment]
@yunnysunny I think you should open a proper issue regarding that. Commenting on a already closed PR doesn't help on visibility for your issue.

**Comment by yunnysunny** [comment]
> @yunnysunny I think you should open a proper issue regarding that. Commenting on a already closed PR doesn't help on visibility for your issue.

Have post an issue https://github.com/Blizzard/node-rdkafka/issues/917
