### ISSUE TITLE
Install fail during node-gyp rebuild

### ISSUE THREAD

**Issue by Vashnak** [Blizzard/node-rdkafka#267]
Hi, I would like to install node-rdkafka but I always get the same error (tried a lot of different versions) .
I'm currently on node 8.6, but also tried 7.10 and 6.10.  

It looks like the problem happens when the "make" command is executed, because a directory already exist. But I don't see why it says it to me. 

Does someone has an idea ? 

LOG:  [log.txt](https://github.com/Blizzard/node-rdkafka/files/1395474/log.txt)

**Comment by webmakersteve** [comment]
Can you purge the node modules directory and try to install again?

**Comment by Vashnak** [comment]
Hi, I already tried it a lot of time without any result :(

**Comment by webmakersteve** [comment]
This directory looks pretty strange to me: ` './-dnode_gyp_module_name=librdkafka'`. Can you run a find in your project directory to search all subfolders for anything with the name `.*librdkafka.*`?

**Comment by Vashnak** [comment]
Okay i'll try as soon as I can, I don't have my pc atm

**Comment by Vashnak** [comment]
Okay I didn't it and found nothing

**Comment by lsancho** [comment]
I've been trying to install for two hours, unsuccessfully so far

```
npm install node-rdkafka --save

> node-rdkafka@2.1.0 install D:\LAB\MaisVendidoPorHora\src\obter-mais-vendido-por-hora\node_modules\node-rdkafka
> node-gyp rebuild


D:\LAB\MaisVendidoPorHora\src\obter-mais-vendido-por-hora\node_modules\node-rdkafka>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Traceback (most recent call last):
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 130, in Load
    params['parallel'], params['root_targets'])
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 2778, in Load
    variables, includes, depth, check, True)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 420, in LoadTargetBuildFile
    build_file_data, PHASE_EARLY, variables, build_file_path)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1295, in ProcessVariablesAndConditionsInDict
    build_file)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1310, in ProcessVariablesAndConditionsInList
    ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1269, in ProcessVariablesAndConditionsInDict
    ProcessConditionsInDict(the_dict, phase, variables, build_file)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1142, in ProcessConditionsInDict
    build_file)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1066, in EvalCondition
    cond_expr, true_dict, false_dict, phase, variables, build_file)
  File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 1100, in EvalSingleCondition
    raise syntax_error
SyntaxError: invalid syntax while evaluating condition '${BUILD_LIBRDKAFKA:-1}==1' in binding.gyp at character 1. gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\LAB\MaisVendidoPorHora\src\obter-mais-vendido-por-hora\node_modules\node-rdkafka
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN omvph@0.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by webmakersteve** [comment]
node-rdkafka does not work on Windows right now. If you want to try windows you can try cloning from the windows branch.

**Comment by Vashnak** [comment]
I forgot to say, I'm on Ubuntu 17.04

**Comment by webmakersteve** [comment]
New build has been pushed to master with drastic differences in the way it is configured to hopefully bring this in better line with librdkafka. Can you try pulling from master to see if it works? I am going to publish it under 2.1.1 in a moment.

**Comment by Vashnak** [comment]
I tried and still have the sale problem, I also tried to install it in an empty folder, no result

**Comment by mattness** [comment]
@Vashnak we don't currently support node 8.x.  Can you please add steps to reproduce for node 6.x and attach npm's log.txt from 6.x?

**Comment by teckays** [comment]
@mattness is there a plan to add node 8.x support in the future?

The error I am getting is:
```
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node-librdkafka.node] Error 1
```

Config:
```
checking for OS or distribution... ok (osx)
checking for C compiler from CC env... failed
checking for gcc (by command)... ok
checking for C++ compiler from CXX env... failed
checking for C++ compiler (g++)... ok
checking executable ld... ok
checking executable nm... ok
checking executable objdump... ok
checking executable strip... ok
checking for debug symbols compiler flag (-g...)... ok
checking for pkgconfig (by command)... failed
checking for install (by command)... failed
checking for PIC (by compile)... ok
checking for GNU-compatible linker options... failed
checking for OSX linker options... ok
checking for GNU linker-script ld flag... failed
checking for Solaris linker-script ld flag... failed (ignore)
checking for __atomic_32 (by compile)... ok
checking for __atomic_64 (by compile)... ok
checking for socket (by compile)... ok
parsing version '0x000b01ff'... ok (0.11.1)
checking for libpthread (by compile)... ok
checking for zlib (by compile)... ok
checking for libcrypto (by compile)... failed (disable)
checking for liblz4 (by compile)... failed (disable)
checking for libssl (by compile)... failed (disable)
checking for libsasl2 (by compile)... ok
checking for crc32chw (by compile)... ok
checking for regex (by compile)... ok
checking for librt (by compile)... failed
checking for strndup (by compile)... ok
checking for strerror_r (by compile)... ok
checking for libdl (by compile)... ok
checking for nm (by env NM)... ok (cached)
Generated Makefile.config
Generated config.h
```

**Comment by RosieCode95** [comment]
@teckays you need a cripto library, on CentOS you can do `yum install -y openssl-devel` etc.

i just had this issue and this fixed it no probs with v8 as of yet

**Comment by teckays** [comment]
@RosieCode95 I am using Debian for my Docker image and I do have the `libsasl2-dev` installed. I tried installing it locally on macOS Sierra as well, same result. `node-rdkafka` installed successfully on my Mac with the previous NodeJS version (which was 7.x I think) but now I've upgraded Node to `v8.7.0` and it fails.

**Comment by RosieCode95** [comment]
yeh prob just have to find the right lib for you, im on 8,7.0 with a clean install of CentOS.7 with no issues.

**Comment by teckays** [comment]
@RosieCode95 just managed to install it on Debian by installing `libssl-dev` instead of `libsasl2-dev`. Still digging to make it work on macOS.

**Comment by RosieCode95** [comment]
👌

**Comment by teckays** [comment]
For everyone else having problems installing `node-rdkafka@2.1.1` on macOS Sierra:

**Error:**
```
ld: library not found for -lcrypto
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/node-librdkafka.node] Error 1
```

**Fix:**
```
⇒  brew install openssl
⇒  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.zshrc
⇒  echo 'export LDFLAGS="-L/usr/local/opt/openssl/lib"' >> ~/.zshrc
⇒  echo 'export CPPFLAGS="-I/usr/local/opt/openssl/include"' >> ~/.zshrc
-   reload terminal
⇒  npm i node-rdkafka
```

**Comment by localzjaz** [comment]
Not sure if you want to consider this in the same issue but I am experiencing errors during docker _(node 6.11.5 alpine build)_ builds with node-rdkafka v2.1.1 . (during node-gyp rebuild).

The same build works with node-rdkafka v2.1.0.

Here is a repository to reproduce the issue: https://github.com/localz/node-rdkafka-build-issues

And the error I get:
```
Step 10/10 : RUN cd /tmp && npm install
 ---> Running in 6e5b6a9cc67d
npm WARN lifecycle node-rdkafka@2.1.1~preinstall: cannot run in wd %s %s (wd=%s) node-rdkafka@2.1.1 node util/configure /tmp/node_modules/.staging/node-rdkafka-19cf018d

> node-rdkafka@2.1.1 install /tmp/node_modules/node-rdkafka
> node-gyp rebuild

make: Entering directory '/tmp/node_modules/node-rdkafka/build'
  CXX(target) Release/obj.target/node-librdkafka/src/binding.o
  CXX(target) Release/obj.target/node-librdkafka/src/callbacks.o
  CXX(target) Release/obj.target/node-librdkafka/src/common.o
  CXX(target) Release/obj.target/node-librdkafka/src/config.o
  CXX(target) Release/obj.target/node-librdkafka/src/connection.o
  CXX(target) Release/obj.target/node-librdkafka/src/errors.o
  CXX(target) Release/obj.target/node-librdkafka/src/kafka-consumer.o
../src/kafka-consumer.cc: In member function 'NodeKafka::Baton NodeKafka::KafkaConsumer::Seek(const RdKafka::TopicPartition&, int)':
../src/kafka-consumer.cc:281:38: error: 'class RdKafka::KafkaConsumer' has no member named 'seek'
   RdKafka::ErrorCode err = consumer->seek(partition, timeout_ms);
                                      ^~~~
../src/kafka-consumer.cc: In member function 'NodeKafka::Baton NodeKafka::KafkaConsumer::OffsetsStore(std::vector<RdKafka::TopicPartition*>&)':
../src/kafka-consumer.cc:388:40: error: 'class RdKafka::KafkaConsumer' has no member named 'offsets_store'; did you mean 'offsetsForTimes'?
     RdKafka::ErrorCode err = consumer->offsets_store(toppars);
                                        ^~~~~~~~~~~~~
```

I'm not sure what the WARN line is trying to tell me. Any thoughts?

**Comment by teckays** [comment]
@localzjaz I'm not sure about the error you have but from my own experience, installing `node-rdkafka` on Alpine is a nightmare. I was in the exact same situation when I decided to switch to Debian Jessie.

Let me know if you want me to share my `Dockerfile`
Hope this helps!

**Comment by chanakyamandava** [comment]
I am using a windows OS, and followed the instructions at https://github.com/Blizzard/node-rdkafka#windows and still the issue with node-gyp rebuild persists.  Can anyone help me resolving this issue. Please find the attached debug log.

[npm-debug.log](https://github.com/Blizzard/node-rdkafka/files/1467582/npm-debug.log)

**Comment by shaoxp** [comment]
met the problem on Ubuntu 22.04.1 LTS with following node version.
error gyp ERR! node -v v16.18.1
error gyp ERR! node-gyp -v v8.4.1
error gyp ERR! not ok
