### ISSUE TITLE
Can't build on nodejs 16.0.0

### ISSUE THREAD

**Issue by bigclap** [Blizzard/node-rdkafka#885]
**Environment Information**
 - OS ubuntu 20.04: 
 - Node Version 16.0.0:
 - NPM Version 7.0.0:
 - C++ Toolchain g++:
 - node-rdkafka version 2.1.0:

**Steps to Reproduce**

Just install package

**node-rdkafka Configuration Settings**
No context. Just can't build it coz in nodejs 16 new ver of v8. 

**Additional context**
`
npm ERR! /home/resation/.cache/node-gyp/16.0.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
npm ERR! /home/resation/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
`
[2021-04-22T16_45_22_674Z-debug.log](https://github.com/Blizzard/node-rdkafka/files/6359955/2021-04-22T16_45_22_674Z-debug.log)

**Comment by bigclap** [comment]
I also tried to change the version of std = c ++ 11 to std = c ++ 14 in bindings.gyp, but unfortunately this prevented the project from building.

**Comment by becerriljc** [comment]
I have the same problem...

**Environment Information**

- OS ubuntu 20.04:
- Node Version 16.0.0:
- NPM Version 7.11.0:
- C++ Toolchain g++:
- node-rdkafka version 2.10.0
- node-gyp 8.0.0

**Steps to Reproduce**

Just install package

node-rdkafka Configuration Settings
No context. Just can't build it coz in nodejs 16 new ver of v8.

Additional context
npm ERR! /home/resation/.cache/node-gyp/16.0.0/include/node/v8-internal.h:452:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?

**Comment by lloiacono** [comment]
I have the same problem but on macOS Big Sur 11.3.1
- Node v16.1.0

**Comment by aferrando-fon** [comment]
Is anyone working on this?

My C++ experience is a bit low, but maybe I can try to work a bit on this on my spare time

**Comment by alferpal** [comment]
Is anyone working on this?

My C++ experience is a bit low, but maybe I can try to work a bit on this on my spare time

**Comment by alferpal** [comment]
Using -std=c++14 with gcc 10, the project builds. Should build using something newer than gcc 8.3 that has support for c++14, which IIRC is what V8 now requires too.

But some e2e fail due to timeout. I'll try to take a look at that at some point this week

**Comment by SergeyFromHell** [comment]
Please, release with that fix!

Tried to install from git from master branch like this:
```
npm i Blizzard/node-rdkafka#master
```
- failing on ./configure.

**Comment by aferrando-fon** [comment]
have you cloned the submodules?

**Comment by SergeyFromHell** [comment]
> have you cloned the submodules?

I have not cloned main repo nor submodules. "npm install" clones repo by itself. Is there any flags for it to clone with submodules? I haven't found any.

**Comment by alferpal** [comment]
I don't think you'll be able to just `npm install` from master, because the published package to npm does contain the submodule with the code of librdkafka

Perhaps what you can do is fork the repository and modify the install behaviour so that it clones submodules before actually building

**Comment by SergeyFromHell** [comment]
I see. What is ETA of a new release with this fix?

**Comment by alferpal** [comment]
That I don't know, as I'm not a maintainer of the package

**Comment by iradul** [comment]
I want to release the new version with the transactions APIs included, hopefully by the end of this week.

**Comment by tgerk** [comment]
Preface: comments since the issue was closed address a different problem than the initial bug report.  It's unfortunate that `npm` (the CLI, not the repository npmjs.org) has a [not-great track record](https://github.com/npm/npm/issues/6700) with installing from github repos.

I made an extension to HighLevelProducer, and now want to distribute a Docker image.  This problem bit me, and this is how I worked around it: `npm pack`

I have a local clone of my fork of node-rdkafka repository.  `npm install` and `npm test` in that working directory is all nice, but I *could not `git install tgerk/node-rdkafka`*.   Instead in my working dir I `npm pack` packed up a tarball that will include C and C++ sources from submodule in deps/librdkafka.  (This is the tarball that would be published to npmjs; it will have a distinguishing version: mine is node-rdkafka-v2.11.0-2.main)  I copied and committed the tarball to my own project's repository, then `npm install [tarball]`
